version: '3.8'

services:
  mydb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - dev.env
  
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    env_file:
      - dev.env
    ports:
      - 8080:8080
    depends_on:
      - mydb
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
  
  api:
    build: ./api/
    ports:
      - 3001:3001
    depends_on:
      - mydb